const express = require('express')
const router = express.Router()

const routesSexo = require('./sexo/routesSexo')
const routesTipoNivel = require('./usuario/routesTipoNivel')
const routesEndereco = require('./endereco/routesEndereco')
const routesUsuario = require('./usuario/routesUsuario')
const routesLogin = require('./routesLogin')
const routesInstituicao = require('./instituicao/routesInstituicao')
const routesCrianca = require('./crianca/routesCrianca')
const routesResponsavel = require('./usuario/routesResponsavel')
const routesRedeSocial = require('./redeSocial/routesRedeSocial')
const routesRedeSocialUsuario = require('./usuario/routesRedeSocialUsuario')
const routesRedeSocialInstituicao = require('./instituicao/routesRedeSocialInstituicao')
const routesTipoInstituicao = require('./instituicao/routesTipoInstituicao')
const routesPublicacaoInstituicao = require('./instituicao/routesPublicacaoInstituicao')
const routesConversa = require('./conversa/routesConversa')
const routesAtividade = require('./atividade/routesAtividade')
const routesCategoria = require('./atividade/routesCategoria')
const routesInscricaoAtividade = require('./atividade/routesInscricaoAtividade')
const routesMatriculaAula = require('./atividade/routesMatriculaAula')

router.use('/sexos', routesSexo)
router.use('/tipoNiveis', routesTipoNivel)
router.use('/enderecos', routesEndereco)
router.use('/usuarios', routesUsuario)
router.use('/instituicoes', routesInstituicao)
router.use('/criancas', routesCrianca)
router.use('/responsaveis', routesResponsavel)
router.use('/redeSociais', routesRedeSocial)
router.use('/redeSocialUsuarios', routesRedeSocialUsuario)
router.use('/redeSocialInstituicoes', routesRedeSocialInstituicao)
router.use('/tipoInstituicoes', routesTipoInstituicao)
router.use('/atividades', routesAtividade)
router.use('/categorias', routesCategoria)
router.use('/login', routesLogin)
router.use('/inscricoes', routesInscricaoAtividade)
router.use('/matriculas', routesMatriculaAula)
router.use('/publicacaoInstituicoes', routesPublicacaoInstituicao)
router.use('/conversas', routesConversa)

module.exports = router