const express = require('express')
const router = express.Router()

const routesSexo = require('./sexo/routesSexo')
const routesTipoNivel = require('./usuario/routesTipoNivel')
const routesEndereco = require('./endereco/routesEndereco')
const routesUsuario = require('./usuario/routesUsuario')
const routesInstituicao = require('./instituicao/routesInstituicao')
const routesCrianca = require('./crianca/routesCrianca')
const routesResponsavel = require('./usuario/routesResponsavel')
const routesRedeSocial = require('./redeSocial/routesRedeSocial')
const routesRedeSocialUsuario = require('./usuario/routesRedeSocialUsuario')
const routesRedeSocialInstituicao = require('./instituicao/routesRedeSocialInstituicao')
const routesTipoInstituicao = require('./instituicao/routesTipoInstituicao')
const routesAtividade = require('./atividade/routesAtividade')
const routesCategoria = require('./atividade/categoria/routesCategoria')

router.use('/sexo', routesSexo)
router.use('/tipoNivel', routesTipoNivel)
router.use('/endereco', routesEndereco)
router.use('/usuario', routesUsuario)
router.use('/instituicoes', routesInstituicao)
router.use('/crianca', routesCrianca)
router.use('/responsavel', routesResponsavel)
router.use('/redeSocial', routesRedeSocial)
router.use('/redeSocialUsuario', routesRedeSocialUsuario)
router.use('/redeSocialInstituicao', routesRedeSocialInstituicao)
router.use('/tipoInstituicao', routesTipoInstituicao)
router.use('/atividade', routesAtividade)
router.use('/categoria', routesCategoria)

module.exports = router